### PR TITLE
Added unit tests and loglevel 'none.'

### PR DESCRIPTION
**Pull request by AshleyGrant**
The changes to config.js and packages.json happened when running the install commands. I think I've tested just about everything there is to test.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
What version of jspm are you using? It looks likes some things have changed in terms of how it manages the config.js file.

**Comment by AshleyGrant** [comment]
I'm using 0.10.0 on Windows

**Comment by EisenbergEffect** [comment]
Can you fix your commit message to match the guidelines? See [here](https://github.com/durandalproject/about/blob/master/CONTRIBUTING.md).

**Comment by AshleyGrant** [comment]
I'm going to close this pull request then redo it with two commits.

**Pull request closed without merging**
